### ISSUE TITLE
Bug w/ Phone - MissingMethodException: .RoundManager.PlayRandomClip()

### ISSUE THREAD

**Issue by Gulfbones** [CassCoffey/LethalPhones#15]
### Describe the bug

If a hoarding bug spawns with a phone (With or without any sound changing mods), It floods the console with Method not found errors, and the bug will never call you. It also seemingly prevents some noises/sounds from playing when this happens.

### Reproducible Test

I just Changed the Hoarding bug Phone Spawn rate to 1, and spawned in a bug.

### Anything else?

the console:

![image](https://github.com/CassCoffey/LethalPhones/assets/113620808/c9eb32cf-ce49-40a2-b81c-c74a10f6d89b)
in `HoardingPhone.cs` line 106 is where it calls `PlayRandomClip`.
It seems like the console wants to say the function is being sent a **single** instead of a **float**.
`.RoundManager.PlayRandomClip(UnityEngine.AudioSource,UnityEngine.AudioClip[],bool,**single**,int)`
Might just need to recompile or force cast the float.

**Comment by CassCoffey** [comment]
This should be patched now with the latest update. Apparently it just needed me to update the .net version the mod used, which is interesting.
